export const SEARCH_AND_SET_PROVAS = "SEARCH_AND_SET_PROVAS";
export const SET_DISCIPLINA = "SET_DISCIPLINA";
export const SET_CURSO = "SET_CURSO";
export const SET_CLASSIFICACAO = "SET_CLASSIFICACAO";
export const SET_PERIODO = "SET_PERIODO";